AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Integration with the Open Exchange Rates service

  '
Globals:
  Function:
    Timeout: 3
Metadata:
  AWS::ServerlessRepo::Application:
    Name: thetis-ims-open-exchange-rates
    Description: Application for integrating Thetis IMS with the open exchange rates
      service.
    Author: thetis-apps
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/4612b8d5aa75b9b9936c9b7b9e6c7e82
    ReadmeUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/7c890caab6020eedf378e4465f289eb4
    Labels:
    - thetis-ims
    HomePageUrl: https://github.com/thetis-apps/OpenExchangeRates
    SemanticVersion: 1.0.1
    SourceCodeUrl: https://github.com/thetis-apps/OpenExchangeRates
Parameters:
  ContextId:
    Type: String
    Description: Context that this application is handling events for.
    MinLength: '1'
  ClientId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientId
  ClientSecret:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientSecret
  ApiKey:
    Type: String
  DevOpsEmail:
    Description: The email address to send mail to when messages in the dead letter
      queue.
    Type: String
    MinLength: 4
Resources:
  ShipmentCreatedHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: Function that runs when a shipment is created within Thetis IMS
      Runtime: nodejs12.x
      Handler: src/handler.shipmentCreatedHandler
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
      Events:
        Request:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
              - public.thetis-ims.com
              detail-type:
              - shipmentCreated
              - inboundShipmentCreated
              - returnShipmentCreated
              detail:
                contextId:
                - Ref: ContextId
      MemorySize: 128
      Timeout: 100
      DeadLetterQueue:
        Type: SQS
        TargetArn:
          Fn::GetAtt:
          - DeadLetterQueue
          - Arn
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/7e3f1310f2f28f5fdbf5c2c94de2938b
    Metadata:
      SamResourceId: ShipmentCreatedHandler
  InitResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - InitializeFunction
        - Arn
      Version: 1
    Metadata:
      SamResourceId: InitResource
  InitializeFunction:
    Type: AWS::Serverless::Function
    DeletionPolicy: Delete
    Properties:
      Handler: src/handler.initializer
      Runtime: nodejs12.x
      MemorySize: 2048
      Timeout: 30
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
          ContextId:
            Ref: ContextId
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/7e3f1310f2f28f5fdbf5c2c94de2938b
    Metadata:
      SamResourceId: InitializeFunction
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties: {}
    Metadata:
      SamResourceId: DeadLetterQueue
  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm when any message is moved to the dead letter queue.
      AlarmActions:
      - Ref: IncidentTopic
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Period: 60
      Namespace: AWS/SQS
      Threshold: '0'
      Unit: Count
      Dimensions:
      - Name: QueueName
        Value:
          Fn::GetAtt:
          - DeadLetterQueue
          - QueueName
      TreatMissingData: notBreaching
      Statistic: Maximum
    Metadata:
      SamResourceId: Alarm
  IncidentTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint:
          Ref: DevOpsEmail
        Protocol: email
      DisplayName: Incidents to be handled by Thetis Devops.
    Metadata:
      SamResourceId: IncidentTopic
