AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Integration with the Open Exchange Rates service

  '
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs16.x
Metadata:
  AWS::ServerlessRepo::Application:
    Name: thetis-ims-open-exchange-rates
    Description: Application for integrating Thetis IMS with the open exchange rates
      service.
    Author: thetis-apps
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/4612b8d5aa75b9b9936c9b7b9e6c7e82
    ReadmeUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/7c890caab6020eedf378e4465f289eb4
    Labels:
    - thetis-ims
    HomePageUrl: https://github.com/thetis-apps/OpenExchangeRates
    SemanticVersion: 1.0.3
    SourceCodeUrl: https://github.com/thetis-apps/OpenExchangeRates
Parameters:
  ContextId:
    Type: String
    Description: Context that this application is handling events for.
    MinLength: '1'
  ClientId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientId
  ClientSecret:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientSecret
  ApiKey:
    Type: String
  DevOpsEmail:
    Description: The email address to send mail to when messages in the dead letter
      queue.
    Type: String
    MinLength: 4
Resources:
  ShipmentCreatedHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: Function that runs when a shipment is created within Thetis IMS
      Handler: src/handler.shipmentCreatedHandler
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
      Events:
        Request:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
              - public.thetis-ims.com
              detail-type:
              - shipmentCreated
              - inboundShipmentCreated
              - returnShipmentCreated
              detail:
                contextId:
                - Ref: ContextId
      MemorySize: 128
      Timeout: 100
      DeadLetterQueue:
        Type: SQS
        TargetArn:
          Fn::GetAtt:
          - DeadLetterQueue
          - Arn
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/d73ff065a47a2a8c2dffa9589334a5f9
    Metadata:
      SamResourceId: ShipmentCreatedHandler
  InitResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - InitializeFunction
        - Arn
      Version: 1
    Metadata:
      SamResourceId: InitResource
  InitializeFunction:
    Type: AWS::Serverless::Function
    DeletionPolicy: Delete
    Properties:
      Handler: src/handler.initializer
      MemorySize: 2048
      Timeout: 30
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
          ContextId:
            Ref: ContextId
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/d73ff065a47a2a8c2dffa9589334a5f9
    Metadata:
      SamResourceId: InitializeFunction
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: alias/aws/sqs
    Metadata:
      SamResourceId: DeadLetterQueue
