version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TestOpenExchangeRates"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3"
s3_prefix = "TestOpenExchangeRates"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ContextId=\"628\" ClientId=\"ThetisClientId\" ClientSecret=\"ThetisClientSecret\" ApiKey=\"5b886445-da07-494a-a37b-02408b8d85e8\" DevOpsEmail=\"lmp@thetis-apps.com\""
