AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Integration with the Open Exchange Rates service
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs24.x

# Metadata to use for the publishing to the SAR
Metadata:
  AWS::ServerlessRepo::Application:
    Name: thetis-ims-open-exchange-rates
    Description: Application for integrating Thetis IMS with the open exchange rates service.
    Author: thetis-apps
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: ['thetis-ims']
    HomePageUrl: https://github.com/thetis-apps/OpenExchangeRates
    SemanticVersion: 2.0.1
    SourceCodeUrl: https://github.com/thetis-apps/OpenExchangeRates

# Parameters of the application 
Parameters:
  ContextId:
    Type: String
    Description: Context that this application is handling events for.
    MinLength: '1'
  ClientId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientId
  ClientSecret:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientSecret
  ApiKey:
    Type: String
  DevOpsEmail:
    Description: The email address to send mail to when messages in the dead letter queue.
    Type: String
    MinLength: 4
    
Resources:

  UpdateRates:
    Type: AWS::Serverless::Function
    Properties:
      Description: Function that updates exchange rates every day at noon.
      Handler: src/handler.updateRates
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
          ContextId:
            Ref: ContextId
      Events:
        Request:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *)

  # Initialisation of Open Exchange Rate integration in context        
  InitResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - InitializeFunction
        - Arn
      Version: 1
  InitializeFunction:
    Type: AWS::Serverless::Function
    DeletionPolicy: Delete
    Properties:
      Handler: src/handler.initializer
      MemorySize: 2048
      Timeout: 30
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
          ContextId:
            Ref: ContextId

  # Our standard monitoring setup      
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: alias/aws/sqs
